<a href="https://colab.research.google.com/github/danunive/-lgebra_Lineal/blob/master/2_1_Lineal_Algebra_Practice_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Question 1.

* Print the sum of matrixes A and B

$$ A =
\left(\begin{array}{cc} 
1 & 2\\
3 & 4\\
5 & 6
\end{array}\right) + B =
\left(\begin{array}{cc} 
6 & 5\\
4 & 3\\
2 & 1 
\end{array}\right)
$$ 

In [6]:
# Answer 1.
'Your code here'
import numpy as np
matriz1 = np.array([[1,3,5],[2,4,6]])
matriz2 = np.array([[6,4,2],[5,3,1]])
print(matriz2-matriz1)



[[ 5  1 -3]
 [ 3 -1 -5]]


# Question 2

* Print the sum of matrix + scalar.

$$ M =
\left(\begin{array}{cc} 
6 & 3\\
9 & 5\\
4 & 8
\end{array}\right) + N =
\left(\begin{array}{cc} 
2.5 \\ 
\end{array}\right)
$$ 

In [0]:
# Answer 2.
##https://www.google.com/search?q=suma+de+una+matriz+por+un+escalar&rlz=1C1CHBF_esCO847CO847&oq=suma+de+una+matriz+por+un+escalar&aqs=chrome..69i57j0l7.5175j0j7&sourceid=chrome&ie=UTF-8

# Question 3.

* Print the transposed matrix of  $J$  -->  $J^t$. 

$$ J =
\left(\begin{array}{cc} 
9 & 2 & 3\\
3 & 7 & 4 \\
5 & 6 & 9
\end{array}\right) 
$$ 

In [11]:
# Answer 3.
'Your code here'
j = np.array([[9,2,3],[3,7,4],[5,6,9]])
jt = j.T
print(jt)

[[9 3 5]
 [2 7 6]
 [3 4 9]]


# Question 4.

* For the $ J ^ t $ matrix, calculate your transpose to obtain the original matrix J. 

$$ J =
\left(\begin{array}{cc} 
9 & 2 & 3\\
3 & 7 & 4 \\
5 & 6 & 9
\end{array}\right) 
$$ 

In [13]:
# Answer 4.
'Your code here'

jt2 = jt.T
print(jt2)


[[9 2 3]
 [3 7 4]
 [5 6 9]]


# Question 5.

* 
What are the missing values? 

$$
\left(\begin{array}{cc} 
? & 2\\
0 & 2
\end{array}\right)
\left(\begin{array}{cc} 
1 & 0 \\ 
1 & ? 
\end{array}\right)
$$ 

 * so that the answer is like this:
$
\left(
 \begin {array}{ll} 
1 & 0 \\
0   & 0
\end{array}
\right)
$

- [ A ] = 1 y 1
- [ B ] = 0 y 1
- [ C ] = 1 y 0
- [ D ] = 0 y 0

*  Print the result and the answer.

In [0]:
# Answer 5.
'your code here'

'your code here'

# Question 6.
* ¿ What is the dot product matrixes  $L$ y $K$ = : ?

$$ L =
\left(\begin{array}{cc} 
3 & 5 \\
7 & 1 \\
\end{array}\right) K =
\left(\begin{array}{cc} 
3 & 12  \\
6 & 4  \\
\end{array}\right)
$$ 

In [20]:
# Answer 6.
'your code here'
L = np.array([[3,5],[7,1]])
K = np.array([[3,12],[6,4]])
LK = L.dot(K)
print(LK)

[[39 56]
 [27 88]]


# Question 7.

* ¿ What is the determinant of the following matrix  ? (Print the answer)

$
\left(
\begin {array}{ll} 
1 & 2 & 0 \\
1 & 2 & 0 \\
0 & 1 & 1 \\
\end{array}
\right)
$

- [ A ] = 1 
- [ B ] = 0 
- [ C ] = 5
- [ D ] = -5



In [23]:
# Answer 7.
p = np.array([[1,2,0],[1,2,0],[0,1,1]])
np.linalg.det(p)

0.0

# Question 8.

* ¿ What is the determinant of the following matrix ? (Print the answer)

$
\left(
\begin {array}{ll} 
0 & 1 & 1 \\
1 & 0 & 0 \\
0 & 0 & 1 \\
\end{array}
\right)
$

- [ A ] = 0 
- [ B ] = -1 
- [ C ] = 3
- [ D ] = 1


In [24]:
# Answer 8.
'your code here'
p2 = np.array([[0,1,1],[1,0,0],[0,0,1]])
np.linalg.det(p2)

-1.0

# Question 9

* ¿What is the missing value?
$$ 
\left(\begin{array}{cc} 
1 & 2 & 3\\
4 & 5 & 6\\
7 & 8 & 9
\end{array}\right) 
\left(\begin{array}{cc} 
0 \\ 
? \\
16 \\
\end{array}\right) =
\left(\begin{array}{cc} 
4 \\ 
10 \\
16 \\
\end{array}\right)
$$ 

In [28]:
y = np.array([[4],[10],[16]])

array([[ 4],
       [10],
       [16]])

In [0]:
o = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [33]:
np.linalg.det(o)

0.0