<a href="https://colab.research.google.com/github/danunive/-lgebra_Lineal/blob/master/Aprender_sobre_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Recursos** **Numpy:**

1.   https://numpy.org/devdocs/user/absolute_beginners.html
2.   https://www.youtube.com/watch?v=GB9ByFAIAH4

3.   https://damianavila.github.io/Python-Cientifico-HCC/3_NumPy.html







# **Listas:**
- Colección de datos
- Puede tener diferentes tipos de datos

# **Numpy:**
- Numeric Python
- Librería de Python
- Alternativa a las listas de python Numpy array
- Puedes hacer operaciones para cada elemento del array
- Tiene un único tipo de datos




In [ ]:
import numpy as np #Importamos la librería de numpy 

In [ ]:
#Vamos a crear una lista
estatura = [1.73, 1.68,1.71, 1.89, 1.79]
print(estatura) #Imprimir la lista
peso = [65.4,59.2,63.6, 88.4, 68.7]
print(peso)

[1.73, 1.68, 1.71, 1.89, 1.79]
[65.4, 59.2, 63.6, 88.4, 68.7]


In [ ]:
#Vamos a convertir la lista a un array de 1dimensión
np_estatura = np.array(estatura)
np_estatura.size ## número total de elementos

5

In [ ]:
#Vamos a convertir la lista a un array de 1dimensión
np_peso = np.array(peso)
np_peso.size

5

In [ ]:
#¿Cómo podemos obtener la dimensión?
np_estatura.ndim

1

In [ ]:
#¿cómo podemos saber el tipo de datos del array?
np_estatura.dtype

dtype('float64')

# **Operaciones**

In [ ]:
#¿Podemos sumar dos listas?
lista = [1,2,3]
lista2 = [5,6,'hola']
lista + lista2 #(¿cuál resultado tengo al sumar dos listas?)

[1, 2, 3, 5, 6, 'hola']

In [ ]:
lista*2

[1, 2, 3, 1, 2, 3]

In [ ]:
#¿Podemos sumar dos array?

In [ ]:
np_lista = np.array(lista) #Convertimos de lista --> array
np_lista2 = np.array(lista2) #Convertimos de lista --> array
np_lista - np_lista2/2

TypeError: ignored

In [ ]:
#Calculamos el BMI
bmi = np_peso / (np_estatura**2)
print(bmi)

[21.85171573 20.97505669 21.75028214 24.7473475  21.44127836]


In [ ]:
¿Cuál es el primer elemento del array?
bmi[0]
#bmi[1]

Object `array` not found.


21.85171572722109

In [ ]:
#Puedo saber cuales son los BMI mayores a 23
bmi > 23

array([False, False, False,  True, False])

In [ ]:
bmi[bmi>23]

array([24.7473475])

# **2D Numpy array**

In [ ]:
#Puedo crear un array 2D con la estatura y el peso
np_medidas = np.array([[estatura],[peso]])
print(np_medidas)

[[[ 1.73  1.68  1.71  1.89  1.79]]

 [[65.4  59.2  63.6  88.4  68.7 ]]]


In [ ]:
#2D Numpy Arrays  --> tiene dos 
np_2d = np.array([[1.73,1.68,1.71,1.89,1.79],
                  [65.4,59.2,63.6,88.4,68.7]])

In [ ]:
np_2d

array([[ 1.73,  1.68,  1.71,  1.89,  1.79],
       [65.4 , 59.2 , 63.6 , 88.4 , 68.7 ]])

In [ ]:
type(np_2d)

numpy.ndarray

In [ ]:
np_2d.shape ## Shape es un atributo de np_2d array

(2, 5)

# **Obtener un elemento** [Fila, Columna]

a[Inicio:fin] 

a[inicio:]  

a[:fin]  

In [4]:
##¿Cómo puedo traer el elemento de la posición fila 0, posición columna 2?
np_2d[0][2]

NameError: ignored

In [5]:
np_2d[0,2]

NameError: ignored

In [ ]:
np_2d[0,:]

In [ ]:
##¿Cómo puedo traer varios elementos según una posición especifica?
np_2d[:,1:3]

# **3D Numpy array**

In [2]:
datos = np.array([[[1,2],
                  [3,5],
                   [8,9]]
                 ,[[4,6],
                   [7,8],
                   [10,11]]])

NameError: ignored

In [3]:
print(datos)

NameError: ignored

In [ ]:
datos[0,1,1]

In [ ]:
datos.ndim

In [ ]:
datos.shape

# **Estadísticas**

In [ ]:
info = np.array([[ 10000, 23],
              [5900 , 25],
              [2000,  26],
              [ 1590, 23]])
info

array([[10000,    23],
       [ 5900,    25],
       [ 2000,    26],
       [ 1590,    23]])

In [ ]:
np.mean(info)

2448.375

In [ ]:
np.mean(info[:,0])

4872.5

In [ ]:
np.median(info[:,0])

3950.0

# **Práctica**

In [1]:
#Crea un np_array (3dimensiones) llamado amigos,
#imprime los atributos de shape,ndtype, size, ndim
#calcula la medi de las edades
#Calcula la mediana de los años de trabajo
#Calcula la máxima edad de los amigos de Tony
#Calcula la minima edad de trabajo de los amigos de Martín
