## Algebra lineal

Perspectiva del fisica > Flecha en el espacio
Perspectiva del programador > Listas
perspectiva del matematico > conjunto de cosas que se pueden sumar y multiplicar
Vector: Fecha en un sistema de coordenadas que parten del origen de coordendas. 
## La suma de vectores
consiste en la suma de término a término.
La multiplicación lo que hace es alargar el vector. Se utilizan los escalares para lograr esto. 

###  "Algebra lineal puede ayudar a los analistas de datos a encontrar patrones en los datos."

In [54]:
v1 = [2,4,6]
v1

[2, 4, 6]

In [4]:
import numpy as np

In [5]:
v2 = np.ones(3) # Vector de solo unos
v2

array([1., 1., 1.])

In [6]:
v3 = np.array([1,3,5]) # pasando una lista a las arrays de numpy
v3

array([1, 3, 5])

In [7]:
v4 = np.arange(1,8) # Utilizando la función arange de numpy
v4

array([1, 2, 3, 4, 5, 6, 7])

Operaciones con vectores
-Suma
-Resta
-Multiplicación

In [12]:
x = np.arange(1,5)
y = np.array([2,4,6,8])
x,y

(array([1, 2, 3, 4]), array([2, 4, 6, 8]))

In [19]:
print(x + y)
print(x-y)
print(x*2)

[ 3  6  9 12]
[-1 -2 -3 -4]
[2 4 6 8]


In [20]:
x @ y

60

In [21]:
np.dot(x,y)

60

In [22]:
a = np.array([3,4])
b = np.array([4,-3])

In [23]:
a @ b

0

# Matrices
- (n x m) n = nro de filas y m = nro de columnas
    Vector fila --- n
    
   Vector Columna ---m
- Normalmente representan los coeficientes de los sistemas de ecuaciones lineales.
- Puedo sumar y restar matrices si tienen las mismas dimensiones
- El espacio nulo Ax = 0

In [27]:
A = np.array([[1,3,2],
             [1,0,0],
             [1,2,2]])
B = np.array([[1,0,5],
             [7,5,0],
             [2,1,1]])
A + B

array([[2, 3, 7],
       [8, 5, 0],
       [3, 3, 3]])

In [28]:
A - B

array([[ 0,  3, -3],
       [-6, -5,  0],
       [-1,  1,  1]])

In [29]:
A.shape ## Ver las dimensiones de la matriz

(3, 3)

In [30]:
A.size ## Ver la cantidad de elementos de una matriz

9

- A x B no es igual a B x A

In [31]:
A = np.arange(1, 13).reshape(3, 4) #matriz de dimension 3x4
A

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [32]:
B = np.arange(8).reshape(4,2) #matriz de dimension 4x2
B

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [33]:
A @ B

array([[ 40,  50],
       [ 88, 114],
       [136, 178]])

 # Matriz Identidad
- Matriz cuadrada (igual número de filas y columnas) y su diagonal principal se compone de 1 y el resto con 0

# Matriz Inversa
- Es aquella matiz cuadrada que hace que la multiplicación A x A-1 sea igual a la matriz identidad
    A x A-1 = I
- Cuando el determinante de la matriz es nulo no existe la matriz inversa.

# Determinante
- Se calcula sobre matriz cuadrada (¿Por qué?)
- Suma de los productos de las diagonales de la matriz en una dirección menos la suma de los productos de las diagonales en la otra dirección se representa con |A|

# Matriz transpuesta
- las filas se transforman en columnas y las columnas se transforman en filas se representa con AT

In [35]:
 I = np.eye(2)
I

array([[1., 0.],
       [0., 1.]])

In [38]:
A = np.array([[4,7],
             [2,6]])

In [40]:

np.linalg.det(A)

10.000000000000002

In [42]:
# Calculando la inversa de A.
A_inv = np.linalg.inv(A)
A_inv

array([[ 0.6, -0.7],
       [-0.2,  0.4]])

In [43]:
# Trasponiendo una matriz
A = np.arange(6).reshape(3, 2)
A

array([[0, 1],
       [2, 3],
       [4, 5]])

In [44]:
np.transpose(A)

array([[0, 2, 4],
       [1, 3, 5]])

# Sistema de ecuaciones lineales
 - (x -2y = 1)
 - (3x + 2y = 11)
 
 - Método de Gauss
# - Eliminación de Gauss- jordan 
     (Las variables deben tener el mismo orden, diagonal = 1 y valores debajo de la diagonal = 0)
     La idea  es utilizar operaciones  elementales hasta llevar un sistema de ecuaciones a una forma escalonada.
- El sistema de ec lineales es consistente si tiene almenos  una solución. Es decir que en la matriz aumentada no tiene una fila [0,0,... m]
- El sistema  de ec lineal tiene tres opciones de solución:
        - única Solución
        - Infinitas Soluciones
        - No tiene Solución
  


In [51]:
 A = np.array([[1, 1, 1],
              [2,4,3],
              [10,11,1]])
A

array([[ 1,  1,  1],
       [ 2,  4,  3],
       [10, 11,  1]])

In [52]:
#Matriz de resultados
b = np.array ([3,9,22])
b

array([ 3,  9, 22])

In [53]:
x = np.linalg.solve(A, b)
x

array([1., 1., 1.])


# Fuentes

https://www.youtube.com/watch?v=wiuEEkP_XuM

https://relopezbriega.github.io/blog/2015/06/14/algebra-lineal-con-python/

https://unipython.com/numpy-algebra/
